<?php
function parse_user_agent($user_agent = null)
{
    if (! is_string($user_agent)) {
        if (array_key_exists('HTTP_USER_AGENT', $_SERVER)) {
            $user_agent = $_SERVER['HTTP_USER_AGENT'];
        } elseif (array_key_exists('http_user_agent', $_SERVER)) {
            $user_agent = $_SERVER['http_user_agent'];
        } else {
            $user_agent = '';
        }
    }

    $user_agent = array(
        'raw' => strtolower($user_agent),
        'browser' => array(
            'name' => 'Unknown browser',
            'version' => 'Unknown version'
        ),
        'os' => array(
            'name' => 'Unknown OS',
            'version' => 'Unknown version'
        ),
        'mobile' => false
    );

    if (strlen($user_agent['raw']) > 0) {
        foreach (array(
            'a1 website download' => 'A1 Website Download',
            'sbl-bot' => 'BlackWidow',
            'avantgo' => 'AvantGo',
            'axel' => 'Axel',
            'bluecrab' => 'BlueCrab',
            'cyotekwebcopy' => 'Cyotek WebCopy',
            'getright' => 'GetRight',
            'isiloxc' => 'iSiloXC',
            'isilox' => 'iSiloX',
            'jobo' => 'JoBo',
            'joc' => 'JOC Web Spider',
            'maemo browser' => 'MicroB',
            'sitesucker' => 'SiteSucker',
            'webcopier' => 'WebCopier',
            'webfetch' => 'webfetch',
            'webstripper' => 'WebStripper',
            'wget' => 'Wget',
            'atomicbrowser' => 'Atomic Web Browser',
            'bingweb' => 'Bing Search App',
            'blazer' => 'Blazer',
            'chromium' => 'Chromium Mobile',
            'acheetahi' => 'CM Browser',
            'coast' => 'Coast',
            'cornowser' => 'Cornowser',
            'ddg' => 'DuckDuckGo Mobile',
            'fbav' => 'Facebook App',
            'focus' => 'Firefox Focus',
            'klar' => 'Firefox Klar',
            'diigobrowser' => 'Diigo',
            'gobrowser' => 'GO Browser',
            'icecat' => 'IceCat Mobile',
            'isivioo' => 'isivioo',
            'kindle' => 'Kindle Browser',
            'minimo' => 'Minimo',
            'mqqbrowser' => 'Mobile QQbrowser',
            'samsungbrowser' => 'Mobile Samsung Browser',
            'ninesky' => 'NineSky',
            'onebrowser' => 'ONE Browser',
            'palemoon' => 'Pale Moon Mobile',
            'polaris' => 'Polaris',
            'puffin' => 'Puffin',
            'semc' => 'SEMC Browser',
            'skyfire' => 'Skyfire',
            'sleipnir' => 'Sleipnir Mobile',
            'teashark' => 'TeaShark',
            'tizen' => 'Tizen Browser',
            'airmail' => 'AirMail',
            'evolution' => 'Evolution',
            'framabird' => 'Framabird',
            'ggpht' => 'Gmail',
            'pocomail' => 'PocoMail',
            'postbox' => 'Postbox',
            'sparrow' => 'Sparrow',
            'thunderbird' => 'Thunderbird',
            'unibox' => 'Unibox',
            'twitterandroid' => 'Twitter App',
            'wib' => 'WIB',
            'bdbrowser_' => 'Baidu Mobile browser',
            'bdbrowser' => 'Baidu Mobile browser',
            'flyflow' => 'Baidu Mobile browser',
            'baidubrowser' => 'Baidu Browser',
            'amigoapp' => 'Amigo Mobile',
            'mb2345browser' => '2345 Explorer Mobile',
            '2345explorer' => '2345 Explorer',
            'pixel xl build' => 'Android webview',
            'htc magic build' => 'Android browser',
            'htc_desire_a8183' => 'Android browser',
            'nexus 10 build' => 'Android browser',
            'iemobile' => 'Internet Explorer Mobile',
            'htc' => 'Yahoo Mobile Mail',
            'zdesktop' => 'Zimbra Desktop',
            'adobeair' => 'Adobe AIR runtime',
            'anemone' => 'Anemone',
            'anglesharp' => 'AngleSharp',
            'axios' => 'axios',
            'csquery' => 'CsQuery',
            'faraday' => 'Faraday',
            'hackney' => 'hackney',
            'indy' => 'Indy Library',
            'manticore' => 'Manticore',
            'mechanize' => 'Mechanize',
            'okhttp' => 'OkHttp',
            'phpcrawl' => 'PHPcrawl',
            'pycurl' => 'PycURL',
            'restsharp' => 'RestSharp',
            'eat' => 'Ruby eat',
            'snoopy' => 'Snoopy',
            'typhoeus' => 'Typhoeus',
            'urlgrabber' => 'urlgrabber',
            'winhttp' => 'WinHTTP',
            'xine' => 'xine',
            'klondike' => 'Klondike',
            'waptiger' => 'WapTiger',
            'winwap' => 'WinWap',
            '2bone' => '2Bone LinkChecker',
            'analyzer' => 'A1 Website Analyzer',
            'checkbot' => 'Checkbot',
            'cynthia' => 'Cynthia',
            'feedvalidator' => 'FeedValidator',
            'htmlparser' => 'HTMLParser',
            'linkexaminer' => 'LinkExaminer',
            'p3p' => 'P3P Validator',
            'fplinkchecker' => 'PHP link checker',
            'checklink' => 'W3C Checklink',
            'i18n' => 'W3C Internationalization Checker',
            'unicorn' => 'W3C Unicorn validator',
            'csscheck' => 'WDG CSSCheck',
            'abilon' => 'Abilon',
            'blogbridge' => 'BlogBridge',
            'bloglines' => 'Bloglines',
            'feeddemon' => 'FeedDemon',
            'greatnews' => 'GreatNews',
            'lucknews' => 'LuckNews',
            'netnewswire' => 'NetNewsWire',
            'newsfox' => 'NewsFox',
            'quiterss' => 'QuiteRSS',
            'reeder' => 'Reeder',
            'rssbandit' => 'Rss Bandit',
            'popper' => 'RSS Popper',
            'rssowl' => 'RSSOwl',
            'applesyndication' => 'Safari RSS reader',
            'sage' => 'Sage',
            'coreplayer' => 'CorePlayer',
            'foobar2000' => 'foobar2000',
            'itunes' => 'iTunes',
            'plex' => 'Plex Media Center',
            'pockettunes' => 'Pocket Tunes',
            'quicktime' => 'QuickTime',
            'rss' => 'RSS Radio',
            'songbird' => 'Songbird',
            'substream' => 'SubStream',
            'xmplay' => 'XMPlay',
            'synapse' => 'Apache Synapse',
            'aria2' => 'aria2',
            'bookdog' => 'Bookdog',
            'cyberduck' => 'Cyberduck',
            'datadog' => 'Datadog Agent',
            'dellwebmonitor' => 'Dell Web Monitor',
            'downloadstudio' => 'DownloadStudio',
            'feedburner' => 'FeedBurner',
            'sync' => 'Funambol Mozilla Sync Client',
            'gvfs' => 'GnomeVFS',
            'earth' => 'Google Earth',
            'googlefriendconnect' => 'Google Friend Connect',
            'listen' => 'Google Listen',
            'gpodder' => 'gPodder',
            'holmes' => 'Holmes',
            'html2jpg' => 'HTML2JPG',
            'igetter' => 'iGetter',
            'jamcast' => 'Jamcast',
            'lftp' => 'LFTP',
            'mucommander' => 'muCommander',
            'nagstamon' => 'Nagstamon',
            'bordermanager' => 'Novell BorderManager',
            'phantomjs' => 'PhantomJS',
            'podkicker' => 'Podkicker',
            'powermarks' => 'Powermarks',
            'offline explorer' => 'Offline Explorer',
            'web downloader' => 'Offline Explorer',
            'downloader' => 'Radio Downloader',
            'szn' => 'Seznam WAP Proxy',
            'azureus' => 'Vuze',
            'whatweb' => 'WhatWeb',
            'winpodder' => 'WinPodder',
            'kuaiso' => '7 Star Browser',
            'ultrabrowser' => 'UltraBrowser',
            'alohabrowser' => 'Aloha Browser',
            'abrowse' => 'ABrowse',
            'acoo' => 'Acoo Browser',
            'alienforce' => 'Alienforce',
            'amaya' => 'Amaya',
            'amigavoyager' => 'Amiga Voyager',
            'mrchrome' => 'Amigo',
            'antfresco' => 'ANT Fresco',
            'aolshield' => 'AOL Shield',
            'aol' => 'AOL Explorer',
            'aolshield' => 'AOL Shield',
            'arora' => 'Arora',
            'asw' => 'Avast SafeZone',
            'avirascout' => 'Avira Scout',
            'sparksafe' => 'Spark Security Browser',
            'spark' => 'Baidu Spark',
            'beamrise' => 'Beamrise',
            'blackbird' => 'Blackbird',
            'blackhawk' => 'BlackHawk',
            'bolt' => 'Bolt',
            'brave' => 'Brave',
            'briskbard' => 'BriskBard',
            'browsex' => 'BrowseX',
            'browzar' => 'Browzar',
            'chedot' => 'Chedot',
            'cheshire' => 'Cheshire',
            'coc' => 'Coc Coc',
            'columbus' => 'Columbus',
            'cometbird' => 'CometBird',
            'comodo' => 'Comodo Dragon',
            'conkeror' => 'Conkeror',
            'coolnovo' => 'CoolNovo',
            'corom' => 'CoRom',
            'crazy' => 'Crazy Browser',
            'cunaguaro' => 'Cunaguaro',
            'cyberdog' => 'Cyberdog',
            'cyberfox' => 'Cyberfox',
            'demeter' => 'Demeter',
            'dillo' => 'Dillo',
            'doczilla' => 'DocZilla',
            'dooble' => 'Dooble',
            'dplus' => 'DPlus',
            'edbrowse' => 'Edbrowse',
            'element' => 'Element Browser',
            'enigma' => 'Enigma browser',
            'epic' => 'Epic',
            'flock' => 'Flock',
            'fluid' => 'Fluid',
            'framafox' => 'Framafox',
            'galeon' => 'Galeon',
            'epiphany' => 'GNOME Web',
            'greenbrowser' => 'GreenBrowser',
            'hydra' => 'Hydra Browser',
            'ibm' => 'IBM WebExplorer',
            'minibrowser' => 'Mini browser',
            'juzibrowser' => 'Orange browser',
            'ibrowse' => 'IBrowse',
            'icab' => 'iCab',
            'iceape' => 'IceApe',
            'icecat' => 'IceCat',
            'icedragon' => 'IceDragon',
            'iceweasel' => 'IceWeasel',
            'internetsurfboard' => 'InternetSurfboard',
            'irider' => 'iRider',
            'iridium' => 'Iridium',
            'iron' => 'Iron',
            'kazehakase' => 'Kazehakase',
            'kinza' => 'Kinza',
            'strata' => 'Kirix Strata',
            'konqueror' => 'Konqueror',
            'kylo' => 'Kylo',
            'lbrowser' => 'LBrowser',
            'elinks' => 'Elinks',
            'links' => 'Links',
            'lobo' => 'Lobo',
            'lolifox' => 'lolifox',
            'lovense' => 'Lovense Browser',
            'edge' => 'Microsoft Edge',
            'midori' => 'Midori',
            'camino' => 'Camino',
            'dolfin' => 'Dolphin',
            'jasmine' => 'Jasmine',
            'min' => 'Min',
            'minibrowser' => 'Mini Browser',
            'mxnitro' => 'MxNitro',
            'myibrow' => 'My Internet Browser',
            'netcaptor' => 'NetCaptor',
            'netpositive' => 'NetPositive',
            'netsurf' => 'NetSurf',
            'offbyone' => 'Off By One',
            'omniweb' => 'OmniWeb',
            'lg-mms-v1.0' => 'LG Phantom Browser',
            'mms' => 'Opera Neon',
            'orca' => 'Orca',
            'oregano' => 'Oregano',
            'otter' => 'Otter',
            'origyn' => 'OWB ',
            'palemoon' => 'Pale Moon',
            'patriott' => 'Patriott',
            'perk' => 'Perk',
            'phaseout' => 'Phaseout',
            'playstation' => 'PS4 Web browser',
            'qiyu' => 'Qiyu Swordfish Browser',
            'qqbrowser' => 'QQbrowser',
            'qupzilla' => 'QupZilla',
            'qutebrowser' => 'qutebrowser',
            'rekonq' => 'Rekonq',
            'roccat' => 'Roccat browser',
            'rockmelt' => 'RockMelt',
            'saayaa' => 'SaaYaa Explorer',
            'secure' => 'Secure browser',
            'shiira' => 'Shiira',
            'sitekiosk' => 'SiteKiosk',
            'skipstone' => 'SkipStone',
            'sleipnir' => 'Sleipnir',
            'slimboat' => 'SlimBoat',
            'slimbrowser' => 'SlimBrowser',
            'sparksafe' => 'Spark Security Browser',
            'sputnikbrowser' => 'Sputnik Browser',
            'stainless' => 'Stainless',
            'sundance' => 'Sundance',
            'sundial' => 'Sundial',
            'superbird' => 'Superbird',
            'swiftweasel' => 'Swiftweasel',
            'sylera' => 'Sylera',
            'taobrowser' => 'Taobao browser',
            'tenfourfox' => 'TenFourFox',
            'theworld' => 'TheWorld Browser',
            'tjusig' => 'Tjusig',
            'tencenttraveler' => 'TT Explorer',
            'ubrowser' => 'UC Browser',
            'navigateur web' => 'Freebox Browser',
            'surf' => 'Surf',
            'blackberry' => 'BlackBerry Browser',
            'usejump' => 'Usejump',
            'uzbl' => 'Uzbl',
            'sparrow' => 'ViaSat Sparrow',
            'vivaldi' => 'Vivaldi',
            'vonkeror' => 'Vonkeror',
            'w3m' => 'w3m',
            'waterfox' => 'Waterfox',
            'wbbrowse' => 'WbBrowse',
            'webianshell' => 'Webian Shell',
            'weltweitimnetzbrowser' => 'Weltweitimnetz Browser',
            'whale' => 'Whale',
            'xvast' => 'Xvast',
            'yrcweblink' => 'YRC Weblink',
            'zbrowser' => 'zBrowser',
            '360' => '360 browser',
            'nintendo 3ds' => '3DS Browser',
            'abolimba.de' => 'Abolimba',
            'amiga-aweb' => 'Amiga Aweb',
            'antgalio' => 'ANT Galio',
            'arachne' => 'Arachne',
            'avant browser' => 'Avant Browser',
            'avantbrowser' => 'Avant Browser',
            'avant' => 'Avant Browser',
            'aviator' => 'Aviator',
            'basilisk' => 'Basilisk',
            'beonex' => 'Beonex',
            'bunjalloo' => 'Bunjalloo',
            'chimera' => 'Camino',
            'charon' => 'Charon',
            'chromium' => 'Chromium',
            'dragon' => 'Chromodo',
            'maxthon' => 'Maxthon',
            'mxbrowser' => 'Maxthon',
            'opr' => 'Opera',
            'nichrome' => 'Rambler browser',
            'salam browser' => 'Salam Browser',
            'sraf' => 'Seraphic Sraf',
            'slack_ssb' => 'Slack App',
            'metasr' => 'Sogou Explorer',
            'tungstenbrowser' => 'Tungsten',
            'webexplorer' => 'Web Explorer',
            'zipzap' => 'ZipZap',
            'bowser' => 'Bowser',
            'sch-f859' => 'Dolphin',
            'ur' => 'UR Browser',
            'instagram' => 'Instagram App',
            'cern-linemode' => 'Line Mode Browser',
            'httrack' => 'HTTrack',
            'line' => 'LINE app',
            'chrome' => 'Chrome',
            'classilla' => 'Classilla',
            'cuam' => 'Cuam',
            'deepnet explorer' => 'Deepnet Explorer',
            'deskbrowse' => 'DeskBrowse',
            'escape' => 'Espial TV Browser',
            'espial' => 'Espial TV Browser',
            'globalmojo' => 'GlobalMojo',
            'kapiko' => 'Kapiko',
            'lunascape' => 'Lunascape',
            'madfox' => 'Madfox',
            'maple' => 'Maple browser',
            'fireweb navigator' => 'Fireweb Navigator',
            'navigator' => 'Netscape Navigator',
            'pb' => 'PirateBrowser',
            'polarity' => 'Polarity',
            'seamonkey' => 'SeaMonkey',
            'swiftfox' => 'Swiftfox',
            'wyzo' => 'Wyzo',
            'fennec' => 'Firefox Mobile',
            'fxios' => 'Firefox Mobile',
            'firefox' => 'Firefox',
            'mosaic' => 'NCSA Mosaic',
            'samsungbrowser' => 'Samsung Browser',
            'sunrisebrowser' => 'Sunrise',
            'sunrise' => 'Sunrise',
            'tulipchain' => 'Tulip Chain',
            'hotjava' => 'HotJava',
            'sun' => 'HotJava',
            'hv3' => 'Hv3',
            'icebrowser' => 'ICE browser',
            'ice browser' => 'ICE browser',
            'kkman' => 'KKman',
            'myie2' => 'Maxthon',
            'netbox' => 'NetBox',
            'opera' => 'Opera',
            'zunewp7' => 'Internet Explorer Mobile',
            'ie' => 'Internet Explorer',
            'lg netcast.tv' => 'LG Web Browser',
            'luakit' => 'luakit',
            'flynxapp' => 'Flynx',
            'lynx' => 'Lynx',
            'multizilla' => 'MultiZilla',
            'webbrowser' => 'Maple browser',
            'netgem' => 'NetBox',
            'netscape6' => 'Netscape Navigator',
            'netscape' => 'Netscape Navigator',
            'nav' => 'Netscape Navigator',
            'oupeng' => 'Opera',
            'qtweb internet browser' => 'QtWeb',
            'retawq' => 'retawq',
            'ryouko' => 'Ryouko',
            'qtcarbrowser' => 'Tesla Car Browser',
            'vimb' => 'Vimb',
            'webpositive' => 'WebPositive',
            'webrender safari' => 'WebRender',
            'bb' => 'BlackBerry Browser',
            'playbook' => 'BlackBerry Browser',
            'crmo' => 'Chrome Mobile',
            'sgh' => 'Chrome Mobile',
            'crios' => 'Chrome Mobile',
            'gsa' => 'Google App',
            'linkedin' => 'LinkedIn App',
            'safari' => 'Safari',
            'vimprobable' => 'Vimprobable',
            'webster' => 'Webster',
            'nintendobrowser' => 'Wii U Internet Browser',
            'wkiosk' => 'wKiosk',
            'worldwideweb' => 'WorldWideWeb',
            'superbot' => 'SuperBot',
            'teleport pro' => 'Teleport Pro',
            'webzip' => 'WebZIP',
            'xaldon_webspider' => 'Xaldon WebSpider',
            'xaldon webspider' => 'Xaldon WebSpider',
            'doris' => 'Doris',
            'ghosterybrowser' => 'Ghostery',
            'trident/7.0; rv:' => 'Internet Explorer',
            'trident/7.0; touch; rv:' => 'Internet Explorer',
            'trident/7.0;' => 'Internet Explorer',
            'cfnetwork' => 'In-App Browser',
            'dalvik' => 'In-App Browser',
            'postmanruntime' => 'Postman',
            'incuto' => 'In-App Browser'
        ) as $browser_find => $browser_name) {
            $position = strpos($user_agent['raw'], strval($browser_find));
            if ($position !== false) {
                $user_agent['browser']['name'] = $browser_name;
                $user_agent['browser']['version'] = explode(' ', trim(substr($user_agent['raw'], $position + strlen($browser_find))));
                $user_agent['browser']['version'] = array_key_exists('0', $user_agent['browser']['version']) ? trim($user_agent['browser']['version'][0], ';/()-') : '';
                $user_agent['browser']['version'] = explode('(', $user_agent['browser']['version']);
                $user_agent['browser']['version'] = array_key_exists('0', $user_agent['browser']['version']) ? trim($user_agent['browser']['version'][0], ';/()-') : '';
                if (substr($user_agent['browser']['version'], 0, 4) == 'http') {
                    $user_agent['browser']['version'] = '';
                }
                break;
            }
        }

        $mobile = array(
            'Brave' => 'Mobile',
            'Chromium' => 'Mobile',
            'Chrome' => 'Mobile',
            'Firefox' => 'Mobile',
            'IceCat' => 'Mobile',
            'IE' => 'Mobile',
            'Iron' => 'Mobile',
            'Maxthon' => 'Mobile',
            'Microsoft Edge' => 'Mobile'
        );

        if (array_key_exists($user_agent['browser']['name'], $mobile)) {
            foreach (array(
                'tablet',
                'mobile',
                'phone',
                'android'
            ) as $find) {
                if (strpos($user_agent['raw'], $find) !== false) {
                    $user_agent['browser']['name'] .= ' ' . $mobile[$user_agent['browser']['name']];
                    $user_agent['mobile'] = true;
                    break;
                }
            }
        } elseif (
            strpos(strtolower($user_agent['browser']['name']), 'mobile') !== false ||
            strpos(strtolower($user_agent['browser']['name']), 'in-app browser') !== false
        ) {
            $user_agent['mobile'] = true;
        }

        foreach (array(
            'windows nt' => 'Windows',
            'winnt' => 'Windows',
            'windows' => 'Windows',
            'iphone os' => 'iOS',
            'iphone' => 'iOS',
            'macintosh; intel mac' => 'Mac',
            'macintosh' => 'Mac',
            'mac' => 'Mac',
            'android' => 'Android',
            'tizen' => 'Tizen 2',
            'linux' => 'Linux',
            'sunos' => 'Solaris',
            'openbsd' => 'OpenBSD',
            'darwin' => 'iOS',
            'postmanruntime' => 'Postman',
            'okhttp' => 'OkHttp',
            'cros armv71' => 'Chrome OS',
            'cros armv7l' => 'Chrome OS',
            'cros x86_64' => 'Chrome OS',
            'cros i686' => 'Chrome OS',
            'cros armv7i' => 'Chrome OS',
            'cros x86_32' => 'Chrome OS',
            'cros' => 'Chrome OS',
            'ios' => 'iOS',
            'bb' => 'BlackBerry OS'
        ) as $os_find => $os) {
            if (strpos($user_agent['raw'], $os_find) !== false) {
                $user_agent['os']['name'] = $os;
                preg_match_all('/' . $os_find . '([a-z0-9._;\/ ]+)/i', $user_agent['raw'], $user_agent['os']['version']);
                if (! (array_key_exists('0', $user_agent['os']['version']) and array_key_exists('0', $user_agent['os']['version'][0]))) {
                    break;
                }
                $user_agent['os']['version'] = $user_agent['os']['version'][0][0];
                $user_agent['os']['version'] = str_replace(array(
                    $os_find,
                    'NT'
                ), '', $user_agent['os']['version']);
                $user_agent['os']['version'] = explode(' like ', $user_agent['os']['version']);
                $user_agent['os']['version'] = strtoupper(trim(str_replace('_', '.', $user_agent['os']['version'][0])));
                $user_agent['os']['version'] = ltrim($user_agent['os']['version'], '/');
                if ($os !== 'Mac') {
                    $user_agent['os']['version'] = explode(';', $user_agent['os']['version'])[0];
                }
                break;
            }
        }
    }

    return array(
        'browser_name' => $user_agent['browser']['name'],
        'browser_version' => $user_agent['browser']['version'],
        'os_name' => $user_agent['os']['name'],
        'os_version' => $user_agent['os']['version'],
        'mobile' => $user_agent['mobile']
    );
}